# Generated by Django 5.2.3 on 2025-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffectbinding',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='requires_value',
            field=models.BooleanField(default=False),
        ),
    ]
