# Generated by Django 5.2.3 on 2025-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cardeffectbinding_value_effect_requires_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='partner_passive',
        ),
        migrations.RemoveField(
            model_name='character',
            name='solo_passive',
        ),
        migrations.AddField(
            model_name='card',
            name='is_character_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='active_ability_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='active_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='class_type',
            field=models.CharField(choices=[('KNIGHT', 'Knight'), ('WIZARD', 'Wizard'), ('BERSERKER', 'Berserker'), ('PRIEST', 'Priest'), ('ASSASSIN', 'Assassin')], default='KNIGHT', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='passive_ability_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='passive_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('SPELL', 'Spell'), ('RITUAL', 'Ritual'), ('ASSET', 'Asset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='partner_energy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='partner_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
