# Generated by Django 5.2.3 on 2025-07-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_condition_effect_trigger_remove_card_abilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cardeffectbinding',
            name='max_triggers_per_turn',
        ),
        migrations.AddField(
            model_name='cardeffectbinding',
            name='restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.restriction'),
        ),
    ]
