# Generated by Django 5.2.3 on 2025-07-10 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_restriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_decks', to='backend.character'),
        ),
        migrations.AddField(
            model_name='deck',
            name='partner_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_decks', to='backend.character'),
        ),
    ]
