# Generated by Django 5.2.3 on 2025-07-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_character_partner_passive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPairSynergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synergy_ability_ref', models.CharField(blank=True, max_length=100)),
                ('synergy_description', models.TextField(blank=True)),
                ('override_active_ability_ref', models.CharField(blank=True, max_length=100)),
                ('override_passive_ability_ref', models.CharField(blank=True, max_length=100)),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_a', to='backend.character')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_b', to='backend.character')),
            ],
            options={
                'unique_together': {('character_a', 'character_b')},
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('PARTNER', 'Partner'), ('RIVAL', 'Rival'), ('LOVER', 'Lover'), ('MENTOR', 'Mentor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_out', to='backend.character')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_in', to='backend.character')),
            ],
            options={
                'unique_together': {('source', 'target', 'relationship_type')},
            },
        ),
    ]
