# Generated by Django 5.2.3 on 2025-07-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cardeffectbinding_trigger_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardeffectbinding',
            name='trigger_zone',
        ),
        migrations.AddField(
            model_name='trigger',
            name='zone',
            field=models.CharField(blank=True, choices=[('board', 'Board'), ('hand', 'Hand'), ('deck', 'Deck'), ('graveyard', 'Graveyard')], help_text="Optional: the zone this trigger applies to (e.g., 'board' for on_friendly_death)", max_length=20, null=True),
        ),
    ]
