# Generated by Django 5.2.3 on 2025-07-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_cardeffectbinding_trigger_zone_trigger_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterPairSynergy',
        ),
    ]
