# Generated by Django 5.2.3 on 2025-07-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_delete_characterpairsynergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='subtype',
            new_name='subtypes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='partner_energy',
        ),
        migrations.RemoveField(
            model_name='character',
            name='solo_energy',
        ),
        migrations.RemoveField(
            model_name='character',
            name='subtype',
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='backstory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='deck_restriction_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='deck_restriction_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='model_file_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='partner_ability_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='partner_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='short_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='solo_bonus_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='solo_bonus_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='subtypes',
            field=models.ManyToManyField(blank=True, related_name='characters', to='backend.subtype'),
        ),
    ]
