# Generated by Django 5.2.3 on 2025-07-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_faction_subtype_rename_subtype_card_subtypes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='subtypes',
        ),
        migrations.AddField(
            model_name='card',
            name='subtypes',
            field=models.ManyToManyField(blank=True, related_name='cards', to='backend.subtype'),
        ),
    ]
