# Generated by Django 5.2.3 on 2025-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_card_color_card_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffectbinding',
            name='target_spec',
            field=models.CharField(blank=True, choices=[('enemy:board', 'Enemy Board'), ('enemy:hero', 'Enemy Hero'), ('enemy:board_or_hero', 'Enemy Board or Hero'), ('friendly:board', 'Friendly Board'), ('self', 'Self'), ('any', 'Any Target')], help_text='Targeting behavior for this effect (used if effect requires target)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='requires_target',
            field=models.BooleanField(default=False),
        ),
    ]
